#!/bin/sh

ACTION="$1"
shift
CODE="$(sed -z 's/\n/ /g' "$1" | sed -r 's/"/\\"/g')"

case "$ACTION" in
"rouler")
	{
		echo "import Francais"
		printf 'runFr "%s"' "$CODE"
	} | cabal repl -v0
	;;
"asa")
	{
		echo "import Francais"
		printf 'runFr "%s"' "$CODE"
	} | cabal repl -v0
	;;
esac

